[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "计算机组织"
authors = [{name = "guoweikang", email = "762666614@qq.com"}]
dynamic = ["version", "description"]
